# Generated by Django 4.0.2 on 2022-02-22 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_app', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('historical', 'historical'), ('horror', 'horror'), ('comedy', 'comedy'), ('crime', 'crime'), ('western', 'western'), ('fantasy', 'fantasy'), ('action', 'action'), ('drama', 'drama'), ('romance', 'romance'), ('thriller', 'thriller'), ('adventure', 'adventure'), ('mystery', 'mystery'), ('political', 'political')], default='historical', max_length=20),
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_likes', to='movie_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
