# Generated by Django 4.0.2 on 2022-02-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_dislikes_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_movie',
            field=models.BooleanField(default=False),
        ),
    ]
