# Generated by Django 4.0.2 on 2022-02-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_movie_like_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='like_movie',
            new_name='is_liked',
        ),
    ]
