# Generated by Django 4.0.2 on 2022-02-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_rename_like_movie_movie_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_visit',
            field=models.IntegerField(default=0),
        ),
    ]
