# Generated by Django 4.0.2 on 2022-02-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_moviecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_liked',
        ),
    ]
