# Generated by Django 4.0.2 on 2022-03-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_moviewatchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieWatchlist',
        ),
    ]
