# Generated by Django 4.0.2 on 2022-02-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.TextField()),
                ('genre', models.CharField(choices=[('historical', 'historical'), ('horror', 'horror'), ('comedy', 'comedy'), ('crime', 'crime'), ('western', 'western'), ('fantasy', 'fantasy'), ('action', 'action'), ('drama', 'drama'), ('romance', 'romance'), ('thriller', 'thriller'), ('adventure', 'adventure'), ('mystery', 'mystery'), ('political', 'political')], default='historical', max_length=20)),
            ],
        ),
    ]
